/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package android.view.panel;

import android.repository.IRepoEcommer;
import javax.swing.JOptionPane;

/**
 *
 * @author Iky
 */
public class SellingPanel1 extends javax.swing.JPanel {

        private final IRepoEcommer repo;
        private final Runnable callback;
    /**
     * Creates new form SellingPanel
     */
    public SellingPanel1(IRepoEcommer repo, Runnable callback) {
        System.out.println("SellingPanel");
        this.repo = repo;
        this.callback = callback;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama_produk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        deskripsi_produk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        harga_produk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stok_produk = new javax.swing.JTextField();
        jButton_tambah = new javax.swing.JButton();
        jButton_kurang = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tambah Produk");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(19, 19, 19))
        );

        jLabel4.setText("Nama Produk");

        nama_produk.setText("Masukkan Nama Produk");
        nama_produk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nama_produkFocusLost(evt);
            }
        });
        nama_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nama_produkMouseClicked(evt);
            }
        });
        nama_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_produkActionPerformed(evt);
            }
        });

        jLabel5.setText("Deskripsi Produk");

        deskripsi_produk.setText("Masukkan Deskripsi Produk");
        deskripsi_produk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                deskripsi_produkFocusLost(evt);
            }
        });
        deskripsi_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deskripsi_produkMouseClicked(evt);
            }
        });
        deskripsi_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsi_produkActionPerformed(evt);
            }
        });

        jLabel6.setText("Harga");

        harga_produk.setText("Atur Harga");
        harga_produk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                harga_produkFocusLost(evt);
            }
        });
        harga_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                harga_produkMouseClicked(evt);
            }
        });
        harga_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_produkActionPerformed(evt);
            }
        });

        jLabel7.setText("Stok");

        stok_produk.setText("0");
        stok_produk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                stok_produkFocusLost(evt);
            }
        });
        stok_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stok_produkMouseClicked(evt);
            }
        });
        stok_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stok_produkActionPerformed(evt);
            }
        });

        jButton_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/android/assets/tambah_icon.png"))); // NOI18N
        jButton_tambah.setBorderPainted(false);
        jButton_tambah.setContentAreaFilled(false);
        jButton_tambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tambahActionPerformed(evt);
            }
        });

        jButton_kurang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/android/assets/kurang_icon.png"))); // NOI18N
        jButton_kurang.setBorderPainted(false);
        jButton_kurang.setContentAreaFilled(false);
        jButton_kurang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_kurangActionPerformed(evt);
            }
        });

        jButton5.setText("Simpan");
        jButton5.setToolTipText("");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(harga_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deskripsi_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(stok_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_tambah)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_kurang)))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskripsi_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(harga_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stok_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_kurang)
                            .addComponent(jButton_tambah))))
                .addGap(64, 64, 64)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nama_produkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nama_produkFocusLost
        if (nama_produk.getText().isEmpty()) {
            nama_produk.setText("Masukkan Nama Produk"); // Kembalikan teks placeholder
        }
    }//GEN-LAST:event_nama_produkFocusLost

    private void nama_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nama_produkMouseClicked
        nama_produk.setText("");
    }//GEN-LAST:event_nama_produkMouseClicked

    private void nama_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_produkActionPerformed

    }//GEN-LAST:event_nama_produkActionPerformed

    private void deskripsi_produkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deskripsi_produkFocusLost
        if (deskripsi_produk.getText().isEmpty()) {
            deskripsi_produk.setText("Masukkan Deskripsi Produk"); // Kembalikan teks placeholder
        }
    }//GEN-LAST:event_deskripsi_produkFocusLost

    private void deskripsi_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deskripsi_produkMouseClicked
        deskripsi_produk.setText("");
    }//GEN-LAST:event_deskripsi_produkMouseClicked

    private void deskripsi_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsi_produkActionPerformed

    }//GEN-LAST:event_deskripsi_produkActionPerformed

    private void harga_produkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_harga_produkFocusLost
        if (harga_produk.getText().isEmpty()) {
            harga_produk.setText("Atur Harga"); // Kembalikan teks placeholder
        }
    }//GEN-LAST:event_harga_produkFocusLost

    private void harga_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_harga_produkMouseClicked
        harga_produk.setText("Rp ");
    }//GEN-LAST:event_harga_produkMouseClicked

    private void harga_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_produkActionPerformed

    }//GEN-LAST:event_harga_produkActionPerformed

    private void stok_produkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stok_produkFocusLost
        if (stok_produk.getText().isEmpty()) {
            stok_produk.setText("0"); // Kembalikan teks placeholder
        }
    }//GEN-LAST:event_stok_produkFocusLost

    private void stok_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stok_produkMouseClicked
        stok_produk.setText("");
    }//GEN-LAST:event_stok_produkMouseClicked

    private void stok_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stok_produkActionPerformed

    }//GEN-LAST:event_stok_produkActionPerformed

    private void jButton_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tambahActionPerformed
        try {
            // Ambil nilai stok dari JTextField
            int stok = Integer.parseInt(stok_produk.getText());

            // Tambah 1 pada stok
            stok += 1;

            // Set nilai baru ke JTextField
            stok_produk.setText(String.valueOf(stok));
        } catch (NumberFormatException e) {
            // Jika stok bukan angka valid, tampilkan pesan error
            JOptionPane.showMessageDialog(this, "Nilai stok tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_tambahActionPerformed

    private void jButton_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_kurangActionPerformed
        try {
            // Ambil nilai stok dari JTextField
            int stok = Integer.parseInt(stok_produk.getText());

            // Kurangi 1 pada stok
            if (stok > 0) { // Pastikan stok tidak negatif
                stok -= 1;
            } else {
                JOptionPane.showMessageDialog(this, "Stok tidak boleh kurang dari 0!", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Set nilai baru ke JTextField
            stok_produk.setText(String.valueOf(stok));
        } catch (NumberFormatException e) {
            // Jika stok bukan angka valid, tampilkan pesan error
            JOptionPane.showMessageDialog(this, "Nilai stok tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_kurangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deskripsi_produk;
    private javax.swing.JTextField harga_produk;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton_kurang;
    private javax.swing.JButton jButton_tambah;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nama_produk;
    private javax.swing.JTextField stok_produk;
    // End of variables declaration//GEN-END:variables
}
