/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Scientific_Calculate;

import android.view.viewAwal;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author com
 */
public class Scientific_Cal extends javax.swing.JFrame {

   
    double firstnum;
    
    double secondnum;
    double result;
    String operation;
    private Object math;
    public Scientific_Cal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sojib = new javax.swing.JTextField();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        numplus = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        numdivide = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        numminus = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        numpoint = new javax.swing.JButton();
        numpn = new javax.swing.JButton();
        numequal = new javax.swing.JButton();
        backspace = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        numrut = new javax.swing.JButton();
        numinto = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        log = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        lnx = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        bin = new javax.swing.JButton();
        hex = new javax.swing.JButton();
        octa = new javax.swing.JButton();
        pai = new javax.swing.JButton();
        round = new javax.swing.JButton();
        JcDistance = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sojib1 = new javax.swing.JTextField();
        sojib2 = new javax.swing.JTextField();
        sojibresult = new javax.swing.JTextField();
        s1 = new javax.swing.JTextField();
        s3 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        sojib.setBackground(new java.awt.Color(255, 204, 255));
        sojib.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sojib.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sojib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sojibActionPerformed(evt);
            }
        });
        sojib.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sojibKeyTyped(evt);
            }
        });

        num8.setBackground(new java.awt.Color(204, 204, 204));
        num8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num9.setBackground(new java.awt.Color(204, 204, 204));
        num9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num7.setBackground(new java.awt.Color(204, 204, 204));
        num7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        numplus.setBackground(new java.awt.Color(153, 255, 255));
        numplus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numplus.setText("+");
        numplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numplusActionPerformed(evt);
            }
        });

        num1.setBackground(new java.awt.Color(204, 204, 204));
        num1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setBackground(new java.awt.Color(204, 204, 204));
        num2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(new java.awt.Color(204, 204, 204));
        num3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        numdivide.setBackground(new java.awt.Color(153, 255, 255));
        numdivide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numdivide.setText("/");
        numdivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numdivideActionPerformed(evt);
            }
        });

        num4.setBackground(new java.awt.Color(204, 204, 204));
        num4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(new java.awt.Color(204, 204, 204));
        num5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num6.setBackground(new java.awt.Color(204, 204, 204));
        num6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        numminus.setBackground(new java.awt.Color(153, 255, 255));
        numminus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numminus.setText("-");
        numminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numminusActionPerformed(evt);
            }
        });

        num0.setBackground(new java.awt.Color(204, 204, 204));
        num0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        numpoint.setBackground(new java.awt.Color(204, 204, 204));
        numpoint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numpoint.setText(".");
        numpoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpointActionPerformed(evt);
            }
        });

        numpn.setBackground(new java.awt.Color(255, 153, 0));
        numpn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numpn.setText("p?");
        numpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpnActionPerformed(evt);
            }
        });

        numequal.setBackground(new java.awt.Color(255, 255, 153));
        numequal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numequal.setText("=");
        numequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numequalActionPerformed(evt);
            }
        });

        backspace.setBackground(new java.awt.Color(204, 204, 255));
        backspace.setForeground(new java.awt.Color(255, 0, 102));
        backspace.setText("←");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 153, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setText("c");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        numrut.setBackground(new java.awt.Color(204, 255, 255));
        numrut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numrut.setText("√");
        numrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numrutActionPerformed(evt);
            }
        });

        numinto.setBackground(new java.awt.Color(153, 255, 255));
        numinto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numinto.setText("*");
        numinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numintoActionPerformed(evt);
            }
        });

        sin.setBackground(new java.awt.Color(255, 255, 204));
        sin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sin.setText("Sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        log.setBackground(new java.awt.Color(255, 51, 255));
        log.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        log.setText("Log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        cos.setBackground(new java.awt.Color(255, 255, 102));
        cos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cos.setText("Cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        lnx.setBackground(new java.awt.Color(255, 153, 0));
        lnx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lnx.setText("lnx");
        lnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnxActionPerformed(evt);
            }
        });

        tan.setBackground(new java.awt.Color(255, 153, 0));
        tan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tan.setText("Tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        bin.setBackground(new java.awt.Color(255, 255, 102));
        bin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bin.setText("Bin");
        bin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binActionPerformed(evt);
            }
        });

        hex.setBackground(new java.awt.Color(255, 255, 102));
        hex.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hex.setText("Hex");
        hex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hexActionPerformed(evt);
            }
        });

        octa.setBackground(new java.awt.Color(255, 153, 0));
        octa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        octa.setText("Octal");
        octa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                octaActionPerformed(evt);
            }
        });

        pai.setBackground(new java.awt.Color(255, 153, 0));
        pai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pai.setText("∏");
        pai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paiActionPerformed(evt);
            }
        });

        round.setBackground(new java.awt.Color(255, 102, 255));
        round.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        round.setText("Round");
        round.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundActionPerformed(evt);
            }
        });

        JcDistance.setBackground(new java.awt.Color(153, 0, 255));
        JcDistance.setEditable(true);
        JcDistance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an option", "Distance", "Speed", "Time", "Force", "Tringle", "Rectangle ", "Square", "Circle", "Mass", "Accelaretion", "Potential energy", "Kinetic energy" }));
        JcDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcDistanceActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 255));
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        sojib1.setBackground(new java.awt.Color(204, 204, 255));
        sojib1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sojib1ActionPerformed(evt);
            }
        });

        sojib2.setBackground(new java.awt.Color(204, 204, 255));

        sojibresult.setBackground(new java.awt.Color(204, 255, 255));

        s1.setBackground(new java.awt.Color(255, 204, 255));
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        s3.setBackground(new java.awt.Color(255, 255, 204));
        s3.setForeground(new java.awt.Color(51, 0, 51));

        s2.setBackground(new java.awt.Color(255, 255, 204));
        s2.setForeground(new java.awt.Color(51, 0, 51));

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/android/assets/home (1).png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jMenu1VetoableChange(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Standerd");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("Unit Conversion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numplus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numminus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numrut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numinto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numdivide, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(numpn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numequal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(round, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(octa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lnx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(sojib, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sojibresult, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JcDistance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sojib1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(sojib2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sojib2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sojib1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sojib, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numrut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numinto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numplus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnx, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numminus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numdivide, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hex, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(octa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(numpn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numequal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(round, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numpoint, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(sojibresult, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        String iNum = sojib.getText()+num9.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num9ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        String iNum = sojib.getText()+num7.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num7ActionPerformed

    private void numplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numplusActionPerformed
        firstnum=Double.parseDouble(sojib.getText());
        sojib.setText(null);
        operation=("+");
    }//GEN-LAST:event_numplusActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        String iNum = sojib.getText()+num1.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num1ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
         String iNum = sojib.getText()+num3.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num3ActionPerformed

    private void numdivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numdivideActionPerformed
        firstnum=Double.parseDouble(sojib.getText());
        sojib.setText(null);
        operation=("/");
    }//GEN-LAST:event_numdivideActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
       String iNum = sojib.getText()+num4.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num4ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        String iNum = sojib.getText()+num6.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num6ActionPerformed

    private void numminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numminusActionPerformed
       firstnum=Double.parseDouble(sojib.getText());
        sojib.setText(null);
        operation=("-");
    }//GEN-LAST:event_numminusActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
       String iNum = sojib.getText()+num0.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num0ActionPerformed

    private void numpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpnActionPerformed
      
      int num=Integer.parseInt(String.valueOf(sojib.getText()));
      int i,count=0;
      for(i=2;i<num;i++)
      {
          if(num%i==0)
          {
             count++;
             break;
          }
      }
      if(count==0)
      {
          sojib.setText("prime");
      }
      else 
      {
          sojib.setText("not prime");
      }
       
      
    }//GEN-LAST:event_numpnActionPerformed

    private void numequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numequalActionPerformed
        String answer;
        secondnum=Double.parseDouble(sojib.getText());
        if(operation=="+")
        {
            result=firstnum+secondnum;
            answer=String.format("%.2f", result);
            sojib.setText(answer);
        }
        else if(operation=="-")
        {
            result=firstnum-secondnum;
            answer=String.format("%.2f", result);
            sojib.setText(answer);
        }
        else if(operation=="*")
        {
            result=firstnum*secondnum;
            answer=String.format("%.2f", result);
            sojib.setText(answer);
        }
        else if(operation=="/")
        {
            result=firstnum/secondnum;
            answer=String.format("%.2f", result);
            sojib.setText(answer);
        }
     
    }//GEN-LAST:event_numequalActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(250, 420);    
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         this.setResizable(true);
        this.setSize(250, 430);
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(390, 420);
           sojib.setSize(350, 39);
     
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
     String bsp=null;
     if(sojib.getText().length()>0)
     {
       StringBuilder strB = new StringBuilder(sojib.getText());
       strB.deleteCharAt(sojib.getText().length()-1);
       bsp = strB.toString();
       sojib.setText(bsp);
     }
    }//GEN-LAST:event_backspaceActionPerformed

    private void numrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numrutActionPerformed
       double ops=Double.parseDouble(String.valueOf(sojib.getText()));
       ops=Math.sqrt(ops);
       sojib.setText(String.valueOf(ops));
    }//GEN-LAST:event_numrutActionPerformed

    private void numintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numintoActionPerformed
       firstnum=Double.parseDouble(sojib.getText());
        sojib.setText(null);
        operation=("*");
    }//GEN-LAST:event_numintoActionPerformed

    private void jMenu1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jMenu1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1VetoableChange

    private void sojibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sojibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sojibActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        String iNum = sojib.getText()+num8.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num8ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        String iNum = sojib.getText()+num5.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num5ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        String iNum = sojib.getText()+num2.getText();
        sojib.setText(iNum);
    }//GEN-LAST:event_num2ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
         
        sojib.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void numpointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpointActionPerformed
       if (!sojib.getText().contains("."))
       {
           sojib.setText(sojib.getText()+ numpoint.getText());
       }
    }//GEN-LAST:event_numpointActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
         double ops=Double.parseDouble(String.valueOf(sojib.getText()));
       ops=Math.log(ops);
       sojib.setText(String.valueOf(ops));
    }//GEN-LAST:event_logActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
         double ops=Double.parseDouble(String.valueOf(sojib.getText()));
       ops=Math.sin(ops);
       sojib.setText(String.valueOf(ops));
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
         double ops=Double.parseDouble(String.valueOf(sojib.getText()));
       ops=Math.cos(ops);
       sojib.setText(String.valueOf(ops));
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
         double ops=Double.parseDouble(String.valueOf(sojib.getText()));
       ops=Math.tan(ops);
       sojib.setText(String.valueOf(ops));
    }//GEN-LAST:event_tanActionPerformed

    private void paiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paiActionPerformed
        double ops;
        ops=(3.1415926535897932384626433832795);
        sojib.setText(String.valueOf(ops));
        
        
    }//GEN-LAST:event_paiActionPerformed

    private void roundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundActionPerformed
          double ops=Double.parseDouble(String.valueOf(sojib.getText()));
       ops=Math.round(ops);
       sojib.setText(String.valueOf(ops));
    }//GEN-LAST:event_roundActionPerformed

    private void binActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binActionPerformed
       int a=Integer.parseInt(sojib.getText());
       sojib.setText(Integer.toString(a,2));
    }//GEN-LAST:event_binActionPerformed

    private void hexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hexActionPerformed
      int a=Integer.parseInt(sojib.getText());
       sojib.setText(Integer.toString(a,16));
    }//GEN-LAST:event_hexActionPerformed

    private void sojibKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sojibKeyTyped
  
    }//GEN-LAST:event_sojibKeyTyped

    private void octaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_octaActionPerformed
        int a=Integer.parseInt(sojib.getText());
       sojib.setText(Integer.toString(a,8));
    }//GEN-LAST:event_octaActionPerformed

    private void lnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnxActionPerformed
         double ops=Double.parseDouble(String.valueOf(sojib.getText()));
       ops=Math.log10(ops);
       sojib.setText(String.valueOf(ops));
    }//GEN-LAST:event_lnxActionPerformed

    private void JcDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcDistanceActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setResizable(true);
        this.setSize(800, 380);
        sojib.setSize(350,39);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void sojib1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sojib1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sojib1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        if((sojib1.getText().equals(""))|| (sojib2.getText().equals("")))
      {
          JOptionPane.showMessageDialog(null, "You must enter value to compute",
                  "DST System",JOptionPane.INFORMATION_MESSAGE);
      }
         double dst1=Double.parseDouble(sojib1.getText());
       double dst2=Double.parseDouble(sojib2.getText());
       double dst3;
      if(JcDistance.getSelectedItem().equals("Distance"))
      {
          s1.setText("Distance=");
          s2.setText("Speed         x");
          s3.setText("Time");
         dst3=dst1*dst2;
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
      else if(JcDistance.getSelectedItem().equals("Time"))
      {
          s1.setText("Time=");
          s2.setText("Distance     ÷");
          s3.setText("Speed");
         dst3=dst1/dst2;
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
       else if(JcDistance.getSelectedItem().equals("Speed"))
      {
          s1.setText("Speed=");
          s2.setText("Distance     ÷");
          s3.setText("Time");
         dst3=dst1/dst2;
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
       else if(JcDistance.getSelectedItem().equals("Force"))
      {
          s1.setText("Force=");
          s2.setText("Mass     x");
          s3.setText("Accelaretion");
         dst3=dst1*dst2;
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
      else if(JcDistance.getSelectedItem().equals("Mass"))
      {
          s1.setText("Mass=");
          s2.setText("Force     ÷");
          s3.setText("Accelaration");
         dst3=dst1/dst2;
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
      else if(JcDistance.getSelectedItem().equals("Accelaretion"))
      {
          s1.setText("Accelaretion=");
          s2.setText("Force     ÷");
          s3.setText("Mass");
         dst3=dst1/dst2;
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
      else if(JcDistance.getSelectedItem().equals("Circle"))
      {
          s1.setText("Circle=");
          s2.setText("pai     x");
          s3.setText("Radius^2");
         dst3=dst1*(dst2*dst2);
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
       else if(JcDistance.getSelectedItem().equals("Tringle"))
      {
          s1.setText("Tringle=");
          s2.setText("Land    x 0.5");
          s3.setText("Hight");
         dst3=0.5*(dst1*dst2);
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
      else if(JcDistance.getSelectedItem().equals("Rectangle "))
      {
          s1.setText("Rectangle=");
          s2.setText("Length    x ");
          s3.setText("Width");
         dst3=dst1*dst2;
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
      else if(JcDistance.getSelectedItem().equals("Kinetic energy"))
      {
          s1.setText("K Energy=");
          s2.setText("Mass    x .5 ");
          s3.setText("Velocity^2");
         dst3=0.5*dst1*(dst2*dst2);
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
      else if(JcDistance.getSelectedItem().equals("Potential energy"))
      {
          s1.setText("P Energy=");
          s2.setText("Mass    x 9.8 ");
          s3.setText("Hight");
         dst3=dst1*dst2*9.8;
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
       else if(JcDistance.getSelectedItem().equals("Square"))
      {
          s1.setText("Square=");
          s2.setText("Side      x");
          s3.setText("Side");
         dst3=dst1*dst2;
         String value=String.format("%.2f",dst3);
         sojibresult.setText(value);
      }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sojibresult.setText(null);
        s1.setText(null);
          s2.setText(null);
          s3.setText(null);
          sojib1.setText(null);
          sojib2.setText(null);
          JcDistance.getSelectedItem().equals(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // tutup frame saat ini
        this.dispose();
        
        //buat dan buka frame Calculator
        viewAwal viewawal = new viewAwal();
        viewawal.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scientific_Cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scientific_Cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcDistance;
    private javax.swing.JButton backspace;
    private javax.swing.JButton bin;
    private javax.swing.JButton clear;
    private javax.swing.JButton cos;
    private javax.swing.JButton hex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton lnx;
    private javax.swing.JButton log;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton numdivide;
    private javax.swing.JButton numequal;
    private javax.swing.JButton numinto;
    private javax.swing.JButton numminus;
    private javax.swing.JButton numplus;
    private javax.swing.JButton numpn;
    private javax.swing.JButton numpoint;
    private javax.swing.JButton numrut;
    private javax.swing.JButton octa;
    private javax.swing.JButton pai;
    private javax.swing.JButton round;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JButton sin;
    private javax.swing.JTextField sojib;
    private javax.swing.JTextField sojib1;
    private javax.swing.JTextField sojib2;
    private javax.swing.JTextField sojibresult;
    private javax.swing.JButton tan;
    // End of variables declaration//GEN-END:variables
}
